Style/Documentation:
  Enabled: false

Layout/TrailingBlankLines:
  Enabled: false

Metrics/AbcSize:
  Max: 20

AllCops:
  Exclude:
    - 'spec/*.rb'
    - 'lib/generators/totoro/templates/*'
    - 'test/**/*'

  TargetRubyVersion: "2.5"