Style/Documentation:
  Enabled: false

Layout/TrailingBlankLines:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

AllCops:
  Exclude:
    - 'spec/*.rb'
    - 'lib/generators/totoro/templates/*'
    - 'test/**/*'

  TargetRubyVersion: "2.5"